### ISSUE TITLE
Benchmark testing results for http piece retrievals

### ISSUE THREAD

**Issue by brendalee** [protocol/bedrock#33]
eta: 2023-02-28
description: Benchmark testing results for http piece retrieval are available for storage / retrievals via Boost.

**Comment by LaurenSpiegel** [comment]
@brendalee , what work is this referring to? who owns?

**Comment by brendalee** [comment]
@LaurenSpiegel this is the benchmark testing / load testing results that we wanted to publish results for (right now we'll only have http). I will move this out to Q2 for now since it won't cover graphsync or bitswap

**Comment by LaurenSpiegel** [comment]
I see. I would just clarify that it is http retrievals rather than storage and other protocols.
