### ISSUE TITLE
IPFS free retrievals from Boost

### ISSUE THREAD

**Issue by TorfinnOlsen** [protocol/bedrock#5]
eta: 2023-02-17
description: The Kubo implementation of IPFS is able to discover content indexed via network indexers, such as cid.contact, over the reframe protocol and retrieve it from Storage Providers running the Bitswap retrieval process with Boost. Only freely available content will be available for this iteration.

**Comment by quickhatche** [comment]
Hello! Checking in to see if there is a status update on this? The issue still says open, with an ETA of 1/2023

**Comment by brendalee** [comment]
it's feature complete, just getting some SP testing now - edited new ETA to Feb 2023
